2020-08-03T13:17:06.2426799+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-03T13:17:06.2681664+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-03T13:17:06.2689143+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-03T13:17:19.6886059+05:30 80000004-0002-fb00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-03T13:17:26.6730697+05:30 80000004-0002-fb00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-03T13:17:59.2321854+05:30 80000012-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.FormatException: String '' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value)
   at MemberOutReachSystem.Controllers.CallTrackController.SaveCallTracking() in D:\data\C_drive\source\repos\MemberOutReachSystem\Controllers\CallTrackController.cs:line 52
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-03T13:44:45.9206171+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-03T13:44:45.9499098+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-03T13:44:45.9503975+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-03T13:44:58.7295172+05:30 80000018-0000-fd00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-03T13:45:03.1884877+05:30 80000018-0000-fd00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
